Requirement already satisfied: python-dateutil in c:\users\sitan\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.7.5)
Requirement already satisfied: six>=1.5 in c:\users\sitan\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil) (1.16.0)
